# Build settings
plugins:
  - octopress-image-tag
  - octopress-solarized
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

repository: samwize/samwize.com

# Site settings
title: "@samwize"
description: > # this means to ignore newlines until "email:"
   ¯\_(ツ)_/¯

email: junda@just2us.com
logo: ""
cover: "/assets/profile/cover-2015.jpg"

permalink: /:year/:month/:day/:title/

name: 'Junda Ong'
author: 'Junda Ong'
author_image: "/assets/profile/profile-pic-2015.jpg"

paginate:	30

url: https://samwize.com
baseurl: ""
#used to display twitter cards
twitter_handle: '@samwize'

#fill in disqus shortname to use disqus
disqus: just2us

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/samwize
    desc: 	Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	stack-overflow
    url:	https://stackoverflow.com/users/242682/samwize
    desc: Ask me on stackoverflow

  - icon:	github
    url:	https://github.com/samwize
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/junda/
    desc:	Connect on LinkedIn

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true # newline becomes <br />

include: [".well-known", ".nojekyll"]

# SEO
twitter:
  username: samwize
  card: summary
author:
  twitter: samwize
facebook:
  admins: 704185456
social:
  name: Junda Ong
  links:
    - https://twitter.com/samwize
    - https://www.facebook.com/ongjunda
    - https://www.linkedin.com/in/junda
    - https://github.com/samwize
